### ISSUE TITLE
utils not found in get_obj_feats.py

### ISSUE THREAD

**Issue by sqiprasanna** [LiamTheronC/Waymo-Motion-Preprocess#1]
Hi,
I was able to remove the below dataLoader error by moving preprocess_exe.py into the main folder and updating line 7 with `from preprocess.preprocess import Waymo_Motion_Preprocess` and it removed dataLoader error. But now I can't find utils folder/file. Please help me with this.

```
utils not found in get_obj_feats.py file
from utils import to_local
```

Update:-
Hi,
I'm getting below error while running preprocess command. I was able to install all packages successfully as mentioned and also install dataloader. Please help me with this.
```

Traceback (most recent call last):
  File "preprocess_exe.py", line 6, in <module>
    from dataLoader.data_loader import Waymo_Motion_DataLoader
ModuleNotFoundError: No module named 'dataLoader'
```

**Comment by LiamTheronC** [comment]
Hi,

I just uploaded the utils.py.
https://github.com/LiamTheronC/Waymo-Motion-Preprocess/blob/main/preprocess/utils.py

Regards,
Liam
